### ISSUE TITLE
In order to improve code quality and its robustness we need to add golint to all golang repositories

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1185]
1. Add a golint workflow. 
2.  Add an option to configure goimpotrts with the separation of local imports. in order to do it run `hack/tools/bin/fixgoimports.sh . if filename is not provided, imports in the entire project will be corrected.
3. Fix all warnings, errors
4. Add an option to automatically verify code before commits. In order to do it, install pre-commit utility:
```
pip install pre-commit
pre-commit install
```

- [x] fybrik/hello-world-module#21
- [x] fybrik/hello-world-read-module#31
- [x] fybrik/data-movement-operator#32
- [x] fybrik/arrow-flight-module#116 
- [x] fybrik/vault-plugin-secrets-kubernetes-reader#19
- [x] json-schema-generator 
- [x] fybrik/fybrik#1187
