### ISSUE TITLE
Update fybrik third party dependencies

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1228]
- [x]  Update goLang to 1.17
- [x] Update supported Kubernetes versions to 1.22 - 1.20 (OpenShift 4.9 runs on K8s 1.22)
- [x] Update helm to v3.8 (we need it due to the security alerts)
- [x]  #1221
- [x] Add support to `cert-manager/v1` api version in data-movement-operator [dmo/pull/44](https://github.com/fybrik/data-movement-operator/pull/44)
- [x] Update certificate manager to v1.6.2 #1255
- [x] #1254
- [x] Update Fybrik modules

**Comment by roytman** [comment]
Done
