### ISSUE TITLE
Change the fields of src and dest to list of arguments in plotter and blueprint

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#1366]
Related to #1354 

Suggested by @shlomitk1 

This issue deals with changing the fields of src and dest to a list of arguments in plotter and blueprint crds in order to simplify the code that generates these resources for the write and read flow.

It requires adjustments to the following fybrik components:

- [x]  fybrik - #1364
- [x] arrow-flight-module - https://github.com/fybrik/arrow-flight-module/issues/141
- [x] hello-world-module - https://github.com/fybrik/hello-world-module/pull/38
- [x] hello-world-read-module - https://github.com/fybrik/hello-world-read-module/pull/54
- [x] implicit-copy modules - https://github.com/fybrik/data-movement-operator/pull/61

**Comment by simanadler** [comment]
@cdoron This will require changes to the airbyte module and transform module you are working on once it's merged too
