### ISSUE TITLE
Integrate OpenMetadata as an opensource data catalog

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1592]
[OpenMetadata](https://open-metadata.org) is a modern open source data catalog. That has connectors to many different data sources, supports data lineage, and many other features.
We need to provide integration of Fybrik with OpenMetadata catalog instead (or in addition) to our demo targeted Katalog.

Tasks:

- [x]  #1593 - Implement OpenMetadata catalog connector
- [x] #1755 - Create a vault plugin to read credentials from OpenMetadata
- [x] #1756 - Update Fybrik and vault helm charts to work with OpenMetadata catalog
- [x]  #1594 - Create demos based on OpenMetadata catalog
- [x]  #1595 - Update Fybrik Web site with explanation about Openmetadata catalog
