### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by flora177** [fybrik/fybrik#1660]
- [x] Define Fybrik release name strategy #1670
- [x] Define Backward compatibility requirements #1675
- [x] Check what which changes can be done in a CRD without changing the CRD schema (Support backward compatibility of CRDs with different schemas can be done with Webhooks. In some Fybrik deployments, Webhooks usage is prohibited.)
- [x] Check taxonomy work for different CRDs with the same schema.
- [ ] Define Connectors (REST API) versioning #1677
- [x] Define versioning of IT config policies #1678
- [x] Define versioning of IT attributes. #1679
- [x] Define Fybrik upgrade procedure  #1379

**Comment by shlomitk1** [comment]
Multi-cluster is a dependency (Razee). We don't define the interface.

**Comment by roytman** [comment]
Implementation of versioning of connectors REST APIs was discussed with our clients, but was put on-hold for now.
Therefore, I'm closing the epic as done.
