### ISSUE TITLE
Implement a component for managing storage in Fybrik

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1737]
**Background:** 
Today we use datashim for dynamic bucket allocation and FybrikStorageAccount resources that represent the available (S3) storage.
We'd like to replace the existing mechanism for a variety of reasons:
- the response is asynchronous - several reconcile cycles may pass before the bucket is ready
- overhead (additional resources such as PVCs are created), sometimes a bucket is not created because one of the PVCs can not be bound, or some other unrelated error.
- no clear error indication if there is an error, or status is OK when no bucket exists
- a limited number of storage types is supported.

Design document: https://github.com/fybrik/fybrik/blob/master/docs/StorageManagement.md

Development tasks (Phase1):
 
- [ ] Provide connection taxonomy layer for s3, db2, kafka, arrow-flight - https://github.com/fybrik/fybrik/issues/1849
- [ ] Changes to FybrikStorageAccount CR - https://github.com/fybrik/fybrik/issues/1744
- [ ] Define StorageManager API - https://github.com/fybrik/fybrik/issues/1850
- [ ] Implement StorageManager with the defined API for s3 using minio sdk - https://github.com/fybrik/fybrik/issues/1852
- [ ] Remove dependency on datashim
- [ ] Add constraints to Optimizer based on storage type
- [ ] Remove hard-coded storage type in manager
- [ ] Update documentation
- [ ] Changes to Airbyte module related to the taxonomy changes

**Comment by simanadler** [comment]
Great summary!  Are there open source alternatives to datashim that could be used?

**Comment by shlomitk1** [comment]
> Great summary! Are there open source alternatives to datashim that could be used?

https://github.com/minio

**Comment by shlomitk1** [comment]
@simanadler There are many types of connections, each requiring a list of properties and credentials. Some of the properties are organization specific, e.g. available hosts+ports and credentials to connect to them, others are defined by the user (name of the table in the database, name of the object to write in a bucket, etc.) A behavior required to create a connection is also dependent on the particular connection and business logic. For example, in order to create a connection X, the behavior will be to connect to a specific server using specific credentials, obtain a token and create a connection using this token. So far, I have not seen any open source projects that deal with preparing/creating a connection. There are open source projects that are able to write to a specific connection (after the user configures all required properties). Also, there are available SDKs for creating S3 buckets, googlesheets, etc.
Examples:
https://github.com/googleapis/google-api-go-client
https://github.com/minio
https://github.com/ncw/dropbox

**Comment by roytman** [comment]
Will it cover SQL data assets? e.g. create schema, table ...

**Comment by shlomitk1** [comment]
> Will it cover SQL data assets? e.g. create schema, table ...

It can, in the future. First, we'll need to decide how the schema is encoded in FybrikApplication.

**Comment by shlomitk1** [comment]
Design document: https://github.com/fybrik/fybrik/blob/master/docs/StorageManagement.md

**Comment by shlomitk1** [comment]
Duplicated
