### ISSUE TITLE
Fybrik Application Taxonomy

### ISSUE THREAD

**Issue by eletonia** [fybrik/fybrik#537]
Task list to create and use a Fybrik Application Taxonomy:
- [x] Finalize the values in Fybrik application JSON schema taxonomy
- [x] Validate schema using @roee88 's [schema validator](https://github.com/roee88/the-mesh-for-data/tree/taxonomy-tool/pkg/taxonomy) #533 
- [x] Move all taxonomy json files to `charts/files` to create config maps #652 
- [x] Write JSON schema taxonomy to config maps #652 
- [x]  Mount config maps to manager deployment as volumeMounts #652 
- [x] Remove smart comments of kubebuilder with hard-coded enums #645 
- [x] Read taxonomy from config map in Fybrik application webhook and validate Fybrik application #645 
- [x] [Check](https://github.com/mesh-for-data/mesh-for-data/blob/664cdbe977f082315194b1a6472661a7036aa1ed/manager/README.md#run-and-debug-locally) if taxonomy validation is working in webhook
- [x] Add validation code to Reconciler and execute if webhooks flag is disabled
- [x] Remove data API strings from the manager code @shlomitk1

**Comment by shlomitk1** [comment]
@eletonia Additional change is to remove smart comments of kubebuilder with hard-coded enums.
