### ISSUE TITLE
Run Vault in non "dev" mode

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#585]
This issue is part of the last milestone of the solution chosen for grading remote modules with access to dataset credentials as described in #140.

The goal of this issue is to run Vault in non dev mode which implies:

1. Enable TLS connection
2. Do not run as root as described in https://learn.hashicorp.com/tutorials/vault/production-hardening (this task can be implemented in dev mode)

To support Vault server with TLS the following changes should be done: 

- Use Vault in standalone mode (Dev mode does not have TLS listeners so we need to use non dev mode (hashicorp/vault#837))
   - Vault server should be unsealed during its initialization phase.
- Create a certificate for Vault server.
   -  The certificate can be created using the process described in: https://docs.cert-manager.io/en/release-0.11/tasks/issuers/setup-ca.html (self-signed cert does not work)
- For multi-cluster an ingress/route should be created with passthrough option

	
To avoid using root token when accessing Vault the following changes should be done: 

- Use Vault Root token for initial Vault configuration:
   - Create users with proper permissions to access Vault. In particular,   the manager and other components  that access Vault should use Vault token.
   - Have the manager to add Vault polices and roles for the modules as they need.
   - The root token should be discarded after initial configuration as recommended in https://learn.hashicorp.com/tutorials/vault/production-hardening
   - There will be no need to create a secret for root token after this change.
   
References:
https://learn.hashicorp.com/tutorials/vault/getting-started-deploy
https://learn.hashicorp.com/tutorials/vault/production-hardening
https://docs.cert-manager.io/en/release-0.11/tasks/issuers/setup-ca.html

**Task list:**
- [ ] Change Vault to non dev mode (possibly  standalone mode)
- [ ] Enable Vault server with TLS
- [ ]  Create a user with proper permissions for the manager and other components which access Vault 
- [ ] Add functionality to the manager to add Vault policies and roles for the modules

**Comment by revit13** [comment]
@roee88 I think so but need to verify. btw, standalone mode is not recommended for production according to https://www.vaultproject.io/docs/platform/k8s/helm/run#helm-chart

**Comment by roee88** [comment]
I don't get the goal here. Are we investing in a production deployment of vault? Why is it our goal?

I thought you just wanted to make the plugins installation compatible with non-dev vault deployment. What are your goals?

**Comment by revit13** [comment]
The goal is to use TLS. As the current dev mode is not working with TLS we need to deploy vault in a non-dev mode. standalone mode is an option,

**Comment by roee88** [comment]
When you say support TLS, do you mean that the manager code currently doesn't handle connecting to a vault instance over TLS? Or are you just referring to the fact that the vault deployment in the Makefile and quick start (which are *not* intended for production) don't deploy with TLS?

**Comment by revit13** [comment]
The latter - the current vault helm installation which uses dev mode do not deploy tls and it actually can not because of the dev mode. Changing to non dev mode such as standalone mode (which is also not proper for production) has implications on how we initialize Vault server and configure it,

**Comment by roee88** [comment]
I don't think that this should be prioritized. Specifically, I think the priority related to this task should be to 1) ensure that the plugins can work with non dev mode  2) validate that manager code is not coded just against http endpoint of vault (i.e. should work with tls).

**Comment by revit13** [comment]
OK thanks. @roee88 @ronenkat I changed the issue description to reflect what you suggested in a private talk, in particular it  now contains tasks regarding enabling TLS and creating Vault user for the manager.

**Comment by revit13** [comment]
@roee88 regarding your list of questions - I would add 3) ensure that the login method to vault is valid - if vault token has a ttl each component will need to login first to get a fresh token and we will need to change the implementation (the token passed in helm chart value will be removed) . There is a notion in Vault of periodic-tokens https://www.vaultproject.io/docs/concepts/tokens#periodic-tokens but I am not sure if we can use that.

**Comment by roytman** [comment]
@revit13, do you have any updates ?

**Comment by revit13** [comment]
Fybrik 1.2.0 contains values file to configure Vault with `ha` mode which includes support for TLS.
