### ISSUE TITLE
Upgrade to Helm 3.7.0

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#817]
As noted in https://github.com/helm/helm/releases/tag/v3.7.0 a few major changes were made to the experimental OCI feature:
 `helm chart` commands were [removed and integrated into helm cli](https://github.com/helm/community/blob/main/hips/hip-0006.md#6-helm-chart-is-removed-integrated-into-rest-of-cli). Backward compatibility [is not guaranteed](https://github.com/helm/community/blob/main/hips/hip-0006.md#backwards-compatibility). For more details: https://github.com/helm/community/blob/main/hips/hip-0006.md.

To upgrade to helm 3.7.0 the following changes need to be done:

- [x] update the commands in `hack/make-rules/helm.mk`
- [x] update the commands in `pkg/helm/`
- [x] Use snapshot versioning for `master` which is the dev version instead of `latest` and `master` tags which are [prohibited](https://github.com/helm/community/blob/main/hips/hip-0006.md#will-i-be-able-to-use-custom-tags-such-as-latest) 
- [x] Update web-page documentation ([example](https://fybrik.io/v0.4/contribute/modules/#module-helm-chart)) which refers to helm chart deployment
- [x] Update  [fybrik/helm](https://github.com/fybrik/helm) dependency 
- [ ] update all the modules that use `helm chart` subcommands under fybrik to use the new helm commands:
   - [x] [arrow-flight-module](https://github.com/fybrik/arrow-flight-module) - https://github.com/fybrik/arrow-flight-module/pull/107
   - [ ] [hello-world-module](https://github.com/fybrik/hello-world-module) -https://github.com/fybrik/hello-world-module/pull/15
   - [ ] [hello-world-read-module](https://github.com/fybrik/hello-world-read-module) -https://github.com/fybrik/hello-world-read-module/pull/22
  - [ ] [data-movement-operator](https://github.com/fybrik/data-movement-operator) - https://github.com/fybrik/data-movement-operator/pull/7

**Comment by roee88** [comment]
Please also check if the requirement to use semver when pushing/pulling is already in place. We're currently using `latest` which according to the original helm plans is invalid.

**Comment by revit13** [comment]
@roee88 Yes, it's in place - I will add that to the list of changes. Thanks. I wonder if it makes sense to use semver [pre-release](https://semver.org/#spec-item-9) 0.0.0-master to denote master and latest charts...

**Comment by roee88** [comment]
For the master use case we should move towards snapshot versioning. For the `latest` use case, is it really required?

**Comment by revit13** [comment]
I never used that... I do not think so.
